### (a) Write python from scratch for 2D Circular convolution using  Doubly Block Circulant matrices method between input=np.array([[1,2,3],[4,5,6],[7,8,9]])and filter=np.array([[1,2,1],[0,0,0],[-1,-2,-1]])

In [102]:
import numpy as np

#input signal

I = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Shape of I is: ', I.shape)
print(I)

#filter

F = np.array([[1, 2, 1], [0, 0, 0], [-1, -2, -1]])
print('Shape of F is: ', F.shape)
print(F)

Shape of I is:  (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of F is:  (3, 3)
[[ 1  2  1]
 [ 0  0  0]
 [-1 -2 -1]]


In [103]:
#Calculating final output size

#Number of rows and columns in input matrix
input_row, input_col = I.shape

#Number of rows and columns in filter matrix
filter_row, filter_col = F.shape

#Calculating dimensions of output matrix
output_row = max(input_row, filter_row)
output_col = max(input_col, filter_col)
print('Dimension of output signal is: ', output_row, output_col)

Dimension of output signal is:  3 3


In [104]:
toeplitz_mat = np.zeros((3,3,3))

In [105]:
def toep(k):
    for i in range(3):
        toeplitz_mat[k][i][0] = F[k][i]
    for i in range(3):
        for j in range(1,3):
            if i-1<0:
                toeplitz_mat[k][i][j] = toeplitz_mat[k][2][j-1]
            else:
                toeplitz_mat[k][i][j] = toeplitz_mat[k][i-1][j-1]

In [106]:
for i in range(3):
    toep(i)

In [107]:
#toeplitz_mat1 = np.flip(toeplitz_mat, 0)
print(toeplitz_mat1)

[[[-1. -1. -2.]
  [-2. -1. -1.]
  [-1. -2. -1.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 1.  1.  2.]
  [ 2.  1.  1.]
  [ 1.  2.  1.]]]


In [92]:
k = np.zeros((3,3))

In [93]:
def toep_ind():
    for i in range(3):
        k[i][0] = i
    for j in range(1,3):
        for i in range(3):
            if i-1<0:
                k[i][j] = k[2][j-1]
            else:
                k[i][j] = k[i-1][j-1]

In [94]:
toep_ind()
print(k)

[[0. 2. 1.]
 [1. 0. 2.]
 [2. 1. 0.]]


In [95]:
h_mat = np.zeros((9,9))

In [96]:
def mat_add(l,m,n):
    for i in range(3):
        for j in range(3):
            row = m+i
            col = n+j
            h_mat[row][col] = toeplitz_mat1[l][i][j]

In [97]:
for j in range(3):
    for i in range(3):
        mat_add(int(k[i][j]),3*i,3*j)

In [98]:
print(h_mat)

[[-1. -1. -2.  1.  1.  2.  0.  0.  0.]
 [-2. -1. -1.  2.  1.  1.  0.  0.  0.]
 [-1. -2. -1.  1.  2.  1.  0.  0.  0.]
 [ 0.  0.  0. -1. -1. -2.  1.  1.  2.]
 [ 0.  0.  0. -2. -1. -1.  2.  1.  1.]
 [ 0.  0.  0. -1. -2. -1.  1.  2.  1.]
 [ 1.  1.  2.  0.  0.  0. -1. -1. -2.]
 [ 2.  1.  1.  0.  0.  0. -2. -1. -1.]
 [ 1.  2.  1.  0.  0.  0. -1. -2. -1.]]


In [99]:
inp_vec = I.reshape((9,1))
print(inp_vec)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [100]:
result = np.dot(h_mat,inp_vec)
result = result.reshape((3,3))

In [101]:
print((-1) * result)

[[-12. -12. -12.]
 [-12. -12. -12.]
 [ 24.  24.  24.]]
