In [1]:
import numpy as np

#input signal

I = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Shape of I is: ', I.shape)
print(I)

#filter

F = np.array([[1, 2, 1], [0, 0, 0], [-1, -2, -1]])
print('Shape of F is: ', F.shape)
print(F)

Shape of I is:  (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of F is:  (3, 3)
[[ 1  2  1]
 [ 0  0  0]
 [-1 -2 -1]]


In [2]:
#Calculating final output size

#Number of rows and columns in input matrix
input_row, input_col = I.shape

#Number of rows and columns in filter matrix
filter_row, filter_col = F.shape

#Calculating dimensions of output matrix
output_row = input_row + filter_row - 1
output_col = input_col + filter_col - 1
print('Dimension of output signal is: ', output_row, output_col)

Dimension of output signal is:  5 5


In [15]:
#zero-padding of filter matrix

filter_zero = np.pad(F, ((output_row - filter_row, 0),
          (0, output_col - filter_col)),
      'constant', constant_values = 0)
print('Zero-padded filter matrix: \n', filter_zero)
filter_zero.shape[0]

Zero-padded filter matrix: 
 [[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 1  2  1  0  0]
 [ 0  0  0  0  0]
 [-1 -2 -1  0  0]]


5

In [6]:
toeplitz_mat = np.zeros((5,5,3))

In [10]:
def toep(k):
    for i in range(5):
        toeplitz_mat[k][i][0] = filter_zero[k][i]
    for i in range(5):
        for j in range(1,3):
            if i-1<0:
                toeplitz_mat[k][i][j] = toeplitz_mat[k][4][j-1]
            else:
                toeplitz_mat[k][i][j] = toeplitz_mat[k][i-1][j-1]

In [11]:
for i in range(5):
    toep(i)

In [42]:
toeplitz_mat1 = np.flip(toeplitz_mat, 0)
print(toeplitz_mat1)

[[[-1.  0.  0.]
  [-2. -1.  0.]
  [-1. -2. -1.]
  [ 0. -1. -2.]
  [ 0.  0. -1.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 1.  0.  0.]
  [ 2.  1.  0.]
  [ 1.  2.  1.]
  [ 0.  1.  2.]
  [ 0.  0.  1.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]]


In [43]:
k = np.zeros((5,3))

In [44]:
def toep_ind():
    for i in range(5):
        k[i][0] = i
    for j in range(1,3):
        for i in range(5):
            if i-1<0:
                k[i][j] = k[4][j-1]
            else:
                k[i][j] = k[i-1][j-1]

In [45]:
toep_ind()
print(k)

[[0. 4. 3.]
 [1. 0. 4.]
 [2. 1. 0.]
 [3. 2. 1.]
 [4. 3. 2.]]


In [46]:
h_mat = np.zeros((25,9))

In [47]:
def mat_add(l,m,n):
    for i in range(5):
        for j in range(3):
            row = m+i
            col = n+j
            h_mat[row][col] = toeplitz_mat1[l][i][j]

In [48]:
for j in range(3):
    for i in range(5):
        mat_add(int(k[i][j]),5*i,3*j)

In [49]:
print(h_mat)

[[-1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -2. -1.  0.  0.  0.  0.  0.  0.]
 [ 0. -1. -2.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -2. -1.  0.  0.  0.  0.]
 [ 0.  0.  0. -1. -2. -1.  0.  0.  0.]
 [ 0.  0.  0.  0. -1. -2.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0. -1.  0.  0.]
 [ 2.  1.  0.  0.  0.  0. -2. -1.  0.]
 [ 1.  2.  1.  0.  0.  0. -1. -2. -1.]
 [ 0.  1.  2.  0.  0.  0.  0. -1. -2.]
 [ 0.  0.  1.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  2.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  2.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  2.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  2.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [50]:
inp_vec = I.reshape((9,1))
print(inp_vec)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [51]:
result = np.dot(h_mat,inp_vec)
result = result.reshape((5,5))

In [53]:
print((-1) * result)

[[  1.   4.   8.   8.   3.]
 [  4.  13.  20.  17.   6.]
 [  6.  18.  24.  18.   6.]
 [ -4. -13. -20. -17.  -6.]
 [ -7. -22. -32. -26.  -9.]]


### (c) Compute number of multiplications required for 2D  linear convolution convolution

In [54]:
print("Total no. of Multiplications :  " + str(512*512*3*3))

Total no. of Multiplications :  2359296
